### ISSUE TITLE
[Bug] unexpected token (Remix)

### ISSUE THREAD

**Issue by pullmann4rent** [tjtanjin/react-chatbotify#99]
Hello,

I installed react chatbotify on remix and got this error

```
/Users/scr/Desktop/24mob/test_vercel/node_modules/react-chatbotify/dist/style.css:1 ...
SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/scr/Desktop/24mob/test_vercel/node_modules/react-chatbotify/dist/index.cjs:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/scr/Desktop/24mob/test_vercel/app/routes/_index.tsx:16:21)

```

what I am doing wrong ?
`
import ChatBot from "react-chatbotify";
const Car = () => {
     return (
     <ChatBot />
   )
}
`

thats my code what I am doing wrong ?

**Comment by tjtanjin** [comment]
Hey @pullmann4rent, what version of remix are you on?

**Comment by tjtanjin** [comment]
Hey @pullmann4rent, are you still having issues?

**Comment by tjtanjin** [comment]
Hey @pullmann4rent, feel free to re-open this if you're still facing issues!
